// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Rebloom",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Rebloom",
            targets: ["AppModule"],
            bundleIdentifier: "com.appoorva.Rebloom",
            teamIdentifier: "296JY5T9QX",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "ReBloom uses the camera so you can capture special moments for your Memory Jar."),
                .microphone(purposeString: "ReBloom uses the microphone so you can send voice missions and voice notes to your partner."),
                .photoLibrary(purposeString: "ReBloom uses your photo library so you can save special moments to your Memory Jar.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)